name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'public/blog-data/**'
      - 'app/**'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.mjs'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "geo-engine-optimization"
          heroku_email: "henihazbay@gmail.com"
          buildpack: "heroku/nodejs"